package engine

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/sanketsaurav/bastion/internal/config"
)

const digestPlaceholder = "@@CONFIG-DIGEST@@"

// GenCompose renders the Compose project for one service, deterministically,
// and returns the content plus its config digest. The digest is computed over
// the rendered file with the digest label blanked, then stamped in — so a
// container's `bastion.config-digest` label always equals the digest of the
// definition that created it (SPEC.md §9.1).
func GenCompose(in *Input, name string) ([]byte, string, error) {
	svc := in.Box.Services[name]
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by bastion %s for box %q. Do not edit; apply overwrites this file.", in.Version, in.BoxID)
	w("name: %s", yamlStr(in.projectName(name)))
	w("services:")
	w("  %s:", name)
	w("    image: %s", yamlStr(svc.Image))
	w("    container_name: %s", yamlStr(in.containerName(name)))
	w("    restart: %s", yamlStr(svc.RestartPolicy))
	if svc.Platform != "" {
		w("    platform: %s", yamlStr(svc.Platform))
	}
	if len(svc.Entrypoint) > 0 {
		w("    entrypoint: %s", jsonArr(svc.Entrypoint))
	}
	if len(svc.Args) > 0 {
		w("    command: %s", jsonArr(svc.Args))
	}
	if svc.WorkingDir != "" {
		w("    working_dir: %s", yamlStr(svc.WorkingDir))
	}
	if svc.User != "" {
		w("    user: %s", yamlStr(svc.User))
	}

	var literals []string
	hasSecret := false
	for _, key := range sortedKeys(svc.Environment) {
		if svc.Environment[key].IsLiteral {
			literals = append(literals, key)
		} else {
			hasSecret = true
		}
	}
	if len(literals) > 0 {
		w("    environment:")
		for _, key := range literals {
			w("      %s: %s", key, yamlStr(svc.Environment[key].Literal))
		}
	}
	if hasSecret {
		// Secret values live in a root-owned env file on the box; the
		// generated definition references the path, never the values
		// (SPEC.md §9.4).
		w("    env_file:")
		w("      - %s", yamlStr(in.secretEnvPath(name)))
	}

	var ports []string
	for _, en := range sortedKeys(svc.Endpoints) {
		ep := svc.Endpoints[en]
		if ep.Visibility == "private" {
			ports = append(ports, fmt.Sprintf("127.0.0.1:%d:%d", ep.EffectiveVMPort(), ep.ContainerPort))
		}
	}
	if len(ports) > 0 {
		w("    ports:")
		for _, p := range ports {
			w("      - %s", yamlStr(p))
		}
	}

	var ephemerals []string
	if len(svc.Mounts) > 0 {
		w("    volumes:")
		for _, m := range svc.Mounts {
			suffix := ""
			if m.ReadOnly {
				suffix = ":ro"
			}
			switch {
			case m.Volume != "":
				vol := in.Box.Volumes[m.Volume]
				if vol.Persistence == "durable" {
					w("      - %s", yamlStr(in.durableVolumeDir(m.Volume)+":"+m.Target+suffix))
				} else {
					ev := in.ephemeralVolume(m.Volume)
					ephemerals = append(ephemerals, ev)
					w("      - %s", yamlStr(ev+":"+m.Target+suffix))
				}
			default:
				w("      - %s", yamlStr(m.Source+":"+m.Target+suffix))
			}
		}
	}

	if svc.Resources != nil {
		if !svc.Resources.Memory.IsZero() {
			w("    mem_limit: %d", svc.Resources.Memory.Bytes())
		}
		if svc.Resources.CPUs > 0 {
			w("    cpus: %s", strconv.FormatFloat(svc.Resources.CPUs, 'f', -1, 64))
		}
	}
	if hc := svc.Healthcheck; hc != nil {
		w("    healthcheck:")
		w("      test: %s", jsonArr(append([]string{"CMD"}, hc.Command...)))
		if !hc.Interval.IsZero() {
			w("      interval: %s", hc.Interval)
		}
		if !hc.Timeout.IsZero() {
			w("      timeout: %s", hc.Timeout)
		}
		if hc.Retries > 0 {
			w("      retries: %d", hc.Retries)
		}
		if !hc.StartPeriod.IsZero() {
			w("      start_period: %s", hc.StartPeriod)
		}
	}
	w("    security_opt:")
	w("      - no-new-privileges:true")
	w("    labels:")
	w("      bastion.box-id: %s", yamlStr(in.BoxID))
	w("      bastion.service: %s", yamlStr(name))
	w("      bastion.image: %s", yamlStr(svc.Image))
	w("      bastion.version: %s", yamlStr(in.Version))
	w("      bastion.config-digest: %s", digestPlaceholder)
	w("networks:")
	w("  default:")
	w("    name: %s", yamlStr(in.networkName()))
	w("    external: true")
	if len(ephemerals) > 0 {
		w("volumes:")
		for _, ev := range ephemerals {
			w("  %s:", ev)
			w("    external: true")
		}
	}

	rendered := b.String()
	digest := sha256hex([]byte(rendered))
	final := strings.Replace(rendered, digestPlaceholder, yamlStr(digest), 1)
	return []byte(final), digest, nil
}

// yamlStr renders a string as a double-quoted YAML scalar. JSON string
// escaping is valid YAML, which keeps this simple and unambiguous ("no",
// "3000", "1.5" all stay strings).
func yamlStr(s string) string {
	data, _ := json.Marshal(s)
	return string(data)
}

// jsonArr renders a string slice as a YAML flow sequence via JSON (a subset
// of YAML), preserving exec-array semantics with no shell parsing.
func jsonArr(items []string) string {
	data, _ := json.Marshal(items)
	return string(data)
}

// serviceApplyOrder returns declared, enabled services topologically sorted by
// dependsOn (validation guarantees acyclicity), name-sorted within ties.
// Cross-project depends_on does not exist in Compose, so ordering is the
// engine's job (SPEC.md Δ13).
func serviceApplyOrder(box *config.Box) []string {
	visited := map[string]bool{}
	var order []string
	var visit func(string)
	visit = func(name string) {
		if visited[name] {
			return
		}
		visited[name] = true
		deps := append([]string(nil), box.Services[name].DependsOn...)
		for _, dep := range deps {
			if _, ok := box.Services[dep]; ok {
				visit(dep)
			}
		}
		order = append(order, name)
	}
	for _, name := range sortedKeys(box.Services) {
		visit(name)
	}
	return order
}

// mutableTag reports whether an image reference should trigger the
// reproducibility warning (SPEC.md §9.2).
func mutableTag(image string) bool {
	if strings.Contains(image, "@sha256:") {
		return false
	}
	slash := strings.LastIndex(image, "/")
	colon := strings.LastIndex(image, ":")
	if colon <= slash {
		return true // untagged → latest
	}
	return image[colon+1:] == "latest"
}
