package engine

import (
	"fmt"
	"strings"
)

// Public HTTPS ingress (SPEC.md §9.8): one bastion-managed Caddy container
// terminates TLS for every public endpoint and routes by hostname to the
// service's port on the box network. User services never publish public
// ports themselves, and bastion never touches DNS, IPs, or firewall rules —
// doctor verifies those instead.

// ingressImage is the pinned reverse-proxy image.
const ingressImage = "docker.io/library/caddy:2.10.2"

// The "_ingress" suffix cannot collide with a user service: service names
// are DNS labels, which never contain underscores. The same property keeps
// the container out of the orphan-service sweep's label guard.
func (in *Input) ingressName() string { return "bastion-" + in.BoxID + "-_ingress" }

// ingressDir holds the generated Caddyfile and Compose project on the box.
func (in *Input) ingressDir() string { return "/var/lib/bastion/ingress/" + in.BoxID }

// ingressDataDir holds Caddy's certificate and ACME state. It lives on the
// data root, outside volumes/, so removal keeps it (re-enabling ingress must
// not re-issue certificates) and the orphan-volume sweep never reports it.
func (in *Input) ingressDataDir() string { return in.Box.Workspace.DataRoot + "/ingress" }

// GenIngress renders the Caddyfile and the ingress Compose project,
// deterministically, plus the digest over both. The digest is stamped into
// the Compose labels, so any Caddyfile change recreates the container.
func GenIngress(in *Input) (caddyfile, compose []byte, digest string, err error) {
	pubs := in.Box.PublicEndpoints()
	if len(pubs) == 0 {
		return nil, nil, "", fmt.Errorf("ingress generation requires at least one public endpoint")
	}

	var c strings.Builder
	fmt.Fprintf(&c, "# Generated by bastion %s for box %q. Do not edit; apply overwrites this file.\n", in.Version, in.BoxID)
	c.WriteString("{\n\tadmin off\n")
	if in.Box.Ingress.ACMEEmail != "" {
		fmt.Fprintf(&c, "\temail %s\n", in.Box.Ingress.ACMEEmail)
	}
	c.WriteString("}\n")
	for _, pe := range pubs { // PublicEndpoints is deterministically ordered
		fmt.Fprintf(&c, "%s {\n\treverse_proxy %s:%d\n}\n", pe.Hostname, pe.Service, pe.ContainerPort)
	}

	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("# Generated by bastion %s for box %q. Do not edit; apply overwrites this file.", in.Version, in.BoxID)
	w("name: %s", yamlStr(in.ingressName()))
	w("services:")
	w("  _ingress:")
	w("    image: %s", yamlStr(ingressImage))
	w("    container_name: %s", yamlStr(in.ingressName()))
	w("    restart: \"unless-stopped\"")
	w("    ports:")
	w("      - \"80:80\"")
	w("      - \"443:443\"")
	w("      - \"443:443/udp\"")
	w("    volumes:")
	w("      - %s", yamlStr(in.ingressDir()+"/Caddyfile:/etc/caddy/Caddyfile:ro"))
	w("      - %s", yamlStr(in.ingressDataDir()+"/data:/data"))
	w("      - %s", yamlStr(in.ingressDataDir()+"/config:/config"))
	w("    security_opt:")
	w("      - no-new-privileges:true")
	w("    labels:")
	w("      bastion.box-id: %s", yamlStr(in.BoxID))
	w("      bastion.ingress: \"1\"")
	w("      bastion.image: %s", yamlStr(ingressImage))
	w("      bastion.version: %s", yamlStr(in.Version))
	w("      bastion.config-digest: %s", digestPlaceholder)
	w("networks:")
	w("  default:")
	w("    name: %s", yamlStr(in.networkName()))
	w("    external: true")

	rendered := b.String()
	caddy := c.String()
	digest = sha256hex([]byte(caddy + "\x00" + rendered))
	final := strings.Replace(rendered, digestPlaceholder, yamlStr(digest), 1)
	return []byte(caddy), []byte(final), digest, nil
}
